// Package brokeracct is the wire contract between the Deevnet API and the
// broker account writer, and the validation both ends apply to it.
//
// It lives in one package on purpose. The API produces these requests and the
// writer consumes them, and a contract defined twice is a contract that drifts.
// Nothing here imports the API's service packages, so the writer stays a small
// binary rather than dragging the whole API onto the messaging VM.
//
// See docs: architecture/substrate/control-plane/broker-account-writer.
package brokeracct

import (
	"encoding/json"
	"fmt"
	"io"
	"regexp"
	"strings"
)

// Version is the only wire version this code speaks. A request carrying
// anything else is refused rather than guessed at: the writer and the API are
// deployed separately, so a mismatch is a real possibility and silence about
// it would be the worst outcome.
const Version = 1

// Operations.
const (
	OpPut    = "put"
	OpDelete = "delete"
)

// Bounds. Every field is bounded, because the writer reads from a network peer
// and an unbounded field is a denial-of-service waiting to be found.
const (
	// MaxRequestBytes caps what the writer will read from stdin at all.
	MaxRequestBytes = 64 << 10

	maxTenant   = 8   // ADR-0002: a tenant name is a PVE SDN zone id
	maxAccount  = 20  // a DNS label's worth, as workload and key names are
	maxPattern  = 256 // one topic filter
	maxPatterns = 32  // per direction
	// A bcrypt hash is exactly this long, and the column is varchar(128).
	bcryptLen = 60
)

// Request is one operation. The caller supplies as little as possible: see
// Account for what the writer derives instead of accepting.
type Request struct {
	Version int    `json:"version"`
	Op      string `json:"op"`
	Tenant  string `json:"tenant"`
	Account string `json:"account"`

	// PasswordHash is the bcrypt hash, never the password. The plaintext is
	// generated by the API, returned once to the tenant, and never crosses
	// this boundary - so the writer cannot learn a device's password because
	// it is never sent one. Empty for a delete.
	PasswordHash string `json:"password_hash,omitempty"`

	// Publish and Subscribe are topic filters, already carrying the tenant's
	// prefix (ADR-0012 §10). The writer re-checks that independently; see
	// Validate.
	Publish   []string `json:"publish,omitempty"`
	Subscribe []string `json:"subscribe,omitempty"`
}

// Response is the single answer. The writer prints exactly one of these and
// exits non-zero whenever OK is false.
type Response struct {
	Version int    `json:"version"`
	OK      bool   `json:"ok"`
	Message string `json:"error,omitempty"`

	// Username is what the writer derived, echoed so the API records the same
	// name it will later delete.
	Username string `json:"username,omitempty"`
	// Existed reports whether the row was already there, which makes a retry
	// distinguishable from a first write in the audit trail without changing
	// the outcome.
	Existed bool `json:"existed,omitempty"`
}

var (
	tenantRE  = regexp.MustCompile(`^[a-z][a-z0-9]{0,7}$`)
	accountRE = regexp.MustCompile(`^[a-z][a-z0-9-]{0,19}$`)
)

// Username is derived, never accepted. Two tenants cannot collide, and a
// caller cannot claim another tenant's account by asking for its name.
func (r Request) Username() string { return r.Tenant + "-" + r.Account }

// Mountpoint and ClientID are fixed by ADR-0012 §10 and are not parameters.
// An account is not tied to a client id, and a tenant does not declare one.
func (r Request) Mountpoint() string { return "" }
func (r Request) ClientID() string   { return "*" }

// Prefix is the only topic space this request may touch.
func (r Request) Prefix() string { return r.Tenant + "/" }

// Decode reads one request, refusing anything oversized or carrying a field
// this version does not know.
//
// Unknown fields are an error rather than ignored: a caller sending a field
// the writer silently drops believes something happened that did not, and the
// one place that must never happen is a permissions grant.
func Decode(rd io.Reader) (Request, error) {
	dec := json.NewDecoder(io.LimitReader(rd, MaxRequestBytes+1))
	dec.DisallowUnknownFields()
	var req Request
	if err := dec.Decode(&req); err != nil {
		return Request{}, fmt.Errorf("request is not the expected JSON: %w", err)
	}
	// Exactly one JSON value. Trailing content means the caller thinks it is
	// having a conversation, and this protocol is one request and one answer.
	if dec.More() {
		return Request{}, fmt.Errorf("request carries trailing content")
	}
	return req, nil
}

// Validate applies every rule both ends must agree on.
//
// On the writer's side this is the last thing between a malformed request and
// a permissions grant. It is NOT a defence against a caller that lies about
// which tenant it is: the writer trusts the authenticated API to name the
// tenant, and enforces only that the request is internally consistent with the
// tenant it claims. See the design's "tenant trust boundary" section.
func (r Request) Validate() error {
	if r.Version != Version {
		return fmt.Errorf("unsupported version %d, this writer speaks %d", r.Version, Version)
	}
	if !tenantRE.MatchString(r.Tenant) {
		return fmt.Errorf("tenant must be 1-%d lowercase alphanumerics starting with a letter", maxTenant)
	}
	if !accountRE.MatchString(r.Account) || strings.HasSuffix(r.Account, "-") {
		return fmt.Errorf("account must be 1-%d lowercase alphanumerics or dashes, starting with a letter and not ending in one", maxAccount)
	}

	switch r.Op {
	case OpDelete:
		// A delete carries identity and nothing else. Anything more means the
		// caller has built the wrong request and should hear so.
		if r.PasswordHash != "" || len(r.Publish) > 0 || len(r.Subscribe) > 0 {
			return fmt.Errorf("a delete carries no password_hash, publish or subscribe")
		}
		return nil
	case OpPut:
	default:
		return fmt.Errorf("op must be %q or %q", OpPut, OpDelete)
	}

	if err := validHash(r.PasswordHash); err != nil {
		return err
	}
	if err := CheckGrant(r.Publish, r.Subscribe); err != nil {
		return err
	}
	if err := validPatterns("publish", r.Publish, r.Prefix()); err != nil {
		return err
	}
	return validPatterns("subscribe", r.Subscribe, r.Prefix())
}

// CheckGrant is the rule about what an account must ask for, stated here so
// both ends apply the same one.
//
// An account has to be able to do something: both lists empty is a mistake
// worth catching rather than a permission worth writing. But ONE empty list is
// normal and allowed - a sensor only publishes, a collector only subscribes -
// and requiring each to declare a pattern for the direction it does not use
// would grant permission nobody wants, which is the opposite of what topic
// confinement exists for (ADR-0012 §10).
func CheckGrant(publish, subscribe []string) error {
	if len(publish) == 0 && len(subscribe) == 0 {
		return fmt.Errorf("an account must have at least one publish or subscribe pattern")
	}
	return nil
}

// validHash accepts only what pgcrypto's crypt() will verify against, which
// was established against the live database rather than assumed: a $2a$
// bcrypt hash of the one length bcrypt produces.
func validHash(h string) error {
	if len(h) != bcryptLen || !strings.HasPrefix(h, "$2a$") {
		return fmt.Errorf("password_hash must be a %d-character $2a$ bcrypt hash", bcryptLen)
	}
	return nil
}

// validPatterns enforces the tenant prefix and MQTT's own wildcard rules.
//
// The prefix is what confines a tenant. The wildcard rules are hygiene: once
// prefixed, a malformed filter still sits under the tenant's name, but it does
// not mean what the tenant intended, and a permission that does not mean what
// was intended is worth refusing.
func validPatterns(field string, pats []string, prefix string) error {
	if len(pats) > maxPatterns {
		return fmt.Errorf("%s has %d patterns, the limit is %d", field, len(pats), maxPatterns)
	}
	for i, p := range pats {
		where := fmt.Sprintf("%s pattern %d", field, i+1)
		switch {
		case p == "":
			return fmt.Errorf("%s is empty", where)
		case len(p) > maxPattern:
			return fmt.Errorf("%s is longer than %d characters", where, maxPattern)
		case !strings.HasPrefix(p, prefix):
			// Deliberately does not echo the pattern: an error message is not
			// a place to reflect a caller's string back over the wire.
			return fmt.Errorf("%s is not under the tenant prefix %q", where, prefix)
		case strings.ContainsRune(p, '%'):
			// % starts a VerneMQ template variable. The API chooses usernames,
			// so there is nothing a tenant could want one for.
			return fmt.Errorf("%s contains %%", where)
		}
		if err := validWildcards(where, p); err != nil {
			return err
		}
	}
	return nil
}

// validWildcards applies MQTT 3.1.1 §4.7: + occupies a whole level, and #
// is the last character of the filter.
func validWildcards(where, pat string) error {
	levels := strings.Split(pat, "/")
	for i, lvl := range levels {
		if strings.Contains(lvl, "+") && lvl != "+" {
			return fmt.Errorf("%s uses + outside a whole level", where)
		}
		if strings.Contains(lvl, "#") {
			if lvl != "#" {
				return fmt.Errorf("%s uses # outside a whole level", where)
			}
			if i != len(levels)-1 {
				return fmt.Errorf("%s uses # before the end of the filter", where)
			}
		}
	}
	return nil
}

// PrefixPattern validates a pattern as the TENANT declares it - relative to
// its own prefix - and returns the absolute form the writer will be sent.
//
// This is the API's half of ADR-0012 §10: "A tenant declares topic patterns
// relative to its prefix. eds declares lightstand/+/scene, and the API stores
// eds/lightstand/+/scene." Prefixing rather than only refusing leaves the
// tenant nothing to get wrong.
//
// The rules live here, beside the ones the writer applies to the result, so
// the two cannot drift into disagreeing about what a valid filter is.
func PrefixPattern(tenantName, relative string) (string, error) {
	switch {
	case relative == "":
		return "", fmt.Errorf("pattern is empty")
	case len(relative) > maxPattern:
		return "", fmt.Errorf("pattern is longer than %d characters", maxPattern)
	case strings.HasPrefix(relative, "/"):
		// A leading slash makes the first level empty, so the prefixed form
		// would be "eds//…" - which is a legal MQTT filter that does not mean
		// what the tenant intended.
		return "", fmt.Errorf("pattern must not start with /")
	case strings.HasPrefix(relative, "$"):
		// $-prefixed topics are reserved. Prefixed it would no longer be
		// reserved, which is worse than refusing it.
		return "", fmt.Errorf("pattern must not start with $")
	case strings.ContainsRune(relative, '%'):
		return "", fmt.Errorf("pattern must not contain %%")
	}
	absolute := tenantName + "/" + relative
	if err := validWildcards("pattern", absolute); err != nil {
		return "", err
	}
	return absolute, nil
}

// PrefixPatterns prefixes a tenant's whole list, reporting which entry failed
// rather than only that one did.
func PrefixPatterns(tenantName, field string, relatives []string) ([]string, error) {
	if len(relatives) == 0 {
		return nil, nil
	}
	if len(relatives) > maxPatterns {
		return nil, fmt.Errorf("%s has %d patterns, the limit is %d", field, len(relatives), maxPatterns)
	}
	out := make([]string, 0, len(relatives))
	for i, rel := range relatives {
		abs, err := PrefixPattern(tenantName, rel)
		if err != nil {
			return nil, fmt.Errorf("%s pattern %d: %w", field, i+1, err)
		}
		out = append(out, abs)
	}
	return out, nil
}

// --- The reserved log level (ADR-0027 §3) -----------------------------------
//
// A device publishes its log messages under one level, immediately after the
// tenant's prefix:
//
//	<tenant>/log/<device>
//
// The substrate's bridge subscribes to `+/log/#` across every tenant and
// carries what it finds into that tenant's (index, 2) partition. That makes
// this level substrate-facing in a way no other level is, so the API reserves
// it: a grant here means "these lines become that tenant's device logs", and
// nothing else.
//
// The rules, from ADR-0027 §3:
//
//   - A DEVICE account may publish exactly its own `<tenant>/log/<device>`.
//     Not a wildcard, not another device's name - a device that could publish
//     under a name it does not own could write log lines attributed to another
//     device, and the store has no way to tell.
//   - A device account may not SUBSCRIBE anywhere in the log space. The ADR
//     names this case: a device has no reason to read its tenant's logs, and
//     an account that both writes and reads them is a way to launder content
//     between devices.
//   - A WORKLOAD account (no device) may subscribe to the log space - its own
//     tenant's, which is all the prefix allows - and may not publish there.
//     A workload with logs of its own ships them to (index, 0) with the
//     tenant's ingest token; it does not put them on the broker for the bridge
//     to pick up.
//
// This is enforced HERE, in the API, and not in the account writer. The writer
// is not told which device an account belongs to, and telling it would widen
// its contract for one rule. What the writer still enforces independently is
// the tenant prefix, which is the rule that keeps tenants apart.

// LogLevel is the reserved level. It is one word in one place: the bridge's
// subscription, the ADR and this check all mean the same level.
const LogLevel = "log"

// CheckLogGrants applies the reservation to one account's ABSOLUTE patterns -
// the prefixed form, as PrefixPatterns returns it.
//
// device is the device the account belongs to, empty for a workload account.
func CheckLogGrants(tenantName, device string, publish, subscribe []string) error {
	own := tenantName + "/" + LogLevel + "/" + device

	for _, p := range publish {
		if !touchesLog(tenantName, p) {
			continue
		}
		if device == "" {
			return fmt.Errorf("only a device account may publish under %s/, and this account has no device (ADR-0027 §3)", LogLevel)
		}
		if p != own {
			// The pattern is not echoed: it came from a caller, and an error
			// message is not a place to reflect a caller's string back.
			return fmt.Errorf("a device account may publish only %s/%s under the reserved %s level", LogLevel, device, LogLevel)
		}
	}

	for _, s := range subscribe {
		if !touchesLog(tenantName, s) {
			continue
		}
		if device != "" {
			return fmt.Errorf("a device account may not subscribe under the reserved %s level (ADR-0027 §3)", LogLevel)
		}
	}
	return nil
}

// touchesLog reports whether a filter could match ANY topic at or under
// <tenant>/log/.
//
// Not a prefix test: `eds/#` and `eds/+/x` reach into the log space without
// spelling it, and a rule that only looked for the literal string would pass
// them. This asks the question the broker will answer at subscribe time -
// could this filter and that space ever meet - which is the only form of the
// question that cannot be worked around by writing the filter differently.
func touchesLog(tenantName, filter string) bool {
	levels := strings.Split(filter, "/")
	for i, want := range []string{tenantName, LogLevel} {
		if i >= len(levels) {
			// The filter ran out: it is shorter than <tenant>/log, so it
			// matches nothing in that space.
			return false
		}
		switch levels[i] {
		case "#":
			// Matches this level and everything below it.
			return true
		case "+", want:
		default:
			return false
		}
	}
	// Both levels matched. Whatever follows - more levels, a wildcard, or
	// nothing at all - is inside the reserved space.
	return true
}
