// Package brokeracct is the wire contract between the Deevnet API and the
// broker account writer, and the validation both ends apply to it.
//
// It lives in one package on purpose. The API produces these requests and the
// writer consumes them, and a contract defined twice is a contract that drifts.
// Nothing here imports the API's service packages, so the writer stays a small
// binary rather than dragging the whole API onto the messaging VM.
//
// See docs: architecture/substrate/control-plane/broker-account-writer.
package brokeracct

import (
	"encoding/json"
	"fmt"
	"io"
	"regexp"
	"strings"
)

// Version is the only wire version this code speaks. A request carrying
// anything else is refused rather than guessed at: the writer and the API are
// deployed separately, so a mismatch is a real possibility and silence about
// it would be the worst outcome.
const Version = 1

// Operations.
const (
	OpPut    = "put"
	OpDelete = "delete"
)

// Bounds. Every field is bounded, because the writer reads from a network peer
// and an unbounded field is a denial-of-service waiting to be found.
const (
	// MaxRequestBytes caps what the writer will read from stdin at all.
	MaxRequestBytes = 64 << 10

	maxTenant   = 8   // ADR-0002: a tenant name is a PVE SDN zone id
	maxAccount  = 20  // a DNS label's worth, as workload and key names are
	maxPattern  = 256 // one topic filter
	maxPatterns = 32  // per direction
	// A bcrypt hash is exactly this long, and the column is varchar(128).
	bcryptLen = 60
)

// Request is one operation. The caller supplies as little as possible: see
// Account for what the writer derives instead of accepting.
type Request struct {
	Version int    `json:"version"`
	Op      string `json:"op"`
	Tenant  string `json:"tenant"`
	Account string `json:"account"`

	// PasswordHash is the bcrypt hash, never the password. The plaintext is
	// generated by the API, returned once to the tenant, and never crosses
	// this boundary - so the writer cannot learn a device's password because
	// it is never sent one. Empty for a delete.
	PasswordHash string `json:"password_hash,omitempty"`

	// Publish and Subscribe are topic filters, already carrying the tenant's
	// prefix (ADR-0012 §10). The writer re-checks that independently; see
	// Validate.
	Publish   []string `json:"publish,omitempty"`
	Subscribe []string `json:"subscribe,omitempty"`
}

// Response is the single answer. The writer prints exactly one of these and
// exits non-zero whenever OK is false.
type Response struct {
	Version int    `json:"version"`
	OK      bool   `json:"ok"`
	Message string `json:"error,omitempty"`

	// Username is what the writer derived, echoed so the API records the same
	// name it will later delete.
	Username string `json:"username,omitempty"`
	// Existed reports whether the row was already there, which makes a retry
	// distinguishable from a first write in the audit trail without changing
	// the outcome.
	Existed bool `json:"existed,omitempty"`
}

var (
	tenantRE  = regexp.MustCompile(`^[a-z][a-z0-9]{0,7}$`)
	accountRE = regexp.MustCompile(`^[a-z][a-z0-9-]{0,19}$`)
)

// Username is derived, never accepted. Two tenants cannot collide, and a
// caller cannot claim another tenant's account by asking for its name.
func (r Request) Username() string { return r.Tenant + "-" + r.Account }

// Mountpoint and ClientID are fixed by ADR-0012 §10 and are not parameters.
// An account is not tied to a client id, and a tenant does not declare one.
func (r Request) Mountpoint() string { return "" }
func (r Request) ClientID() string   { return "*" }

// Prefix is the only topic space this request may touch.
func (r Request) Prefix() string { return r.Tenant + "/" }

// Decode reads one request, refusing anything oversized or carrying a field
// this version does not know.
//
// Unknown fields are an error rather than ignored: a caller sending a field
// the writer silently drops believes something happened that did not, and the
// one place that must never happen is a permissions grant.
func Decode(rd io.Reader) (Request, error) {
	dec := json.NewDecoder(io.LimitReader(rd, MaxRequestBytes+1))
	dec.DisallowUnknownFields()
	var req Request
	if err := dec.Decode(&req); err != nil {
		return Request{}, fmt.Errorf("request is not the expected JSON: %w", err)
	}
	// Exactly one JSON value. Trailing content means the caller thinks it is
	// having a conversation, and this protocol is one request and one answer.
	if dec.More() {
		return Request{}, fmt.Errorf("request carries trailing content")
	}
	return req, nil
}

// Validate applies every rule both ends must agree on.
//
// On the writer's side this is the last thing between a malformed request and
// a permissions grant. It is NOT a defence against a caller that lies about
// which tenant it is: the writer trusts the authenticated API to name the
// tenant, and enforces only that the request is internally consistent with the
// tenant it claims. See the design's "tenant trust boundary" section.
func (r Request) Validate() error {
	if r.Version != Version {
		return fmt.Errorf("unsupported version %d, this writer speaks %d", r.Version, Version)
	}
	if !tenantRE.MatchString(r.Tenant) {
		return fmt.Errorf("tenant must be 1-%d lowercase alphanumerics starting with a letter", maxTenant)
	}
	if !accountRE.MatchString(r.Account) || strings.HasSuffix(r.Account, "-") {
		return fmt.Errorf("account must be 1-%d lowercase alphanumerics or dashes, starting with a letter and not ending in one", maxAccount)
	}

	switch r.Op {
	case OpDelete:
		// A delete carries identity and nothing else. Anything more means the
		// caller has built the wrong request and should hear so.
		if r.PasswordHash != "" || len(r.Publish) > 0 || len(r.Subscribe) > 0 {
			return fmt.Errorf("a delete carries no password_hash, publish or subscribe")
		}
		return nil
	case OpPut:
	default:
		return fmt.Errorf("op must be %q or %q", OpPut, OpDelete)
	}

	if err := validHash(r.PasswordHash); err != nil {
		return err
	}
	if err := validPatterns("publish", r.Publish, r.Prefix()); err != nil {
		return err
	}
	return validPatterns("subscribe", r.Subscribe, r.Prefix())
}

// validHash accepts only what pgcrypto's crypt() will verify against, which
// was established against the live database rather than assumed: a $2a$
// bcrypt hash of the one length bcrypt produces.
func validHash(h string) error {
	if len(h) != bcryptLen || !strings.HasPrefix(h, "$2a$") {
		return fmt.Errorf("password_hash must be a %d-character $2a$ bcrypt hash", bcryptLen)
	}
	return nil
}

// validPatterns enforces the tenant prefix and MQTT's own wildcard rules.
//
// The prefix is what confines a tenant. The wildcard rules are hygiene: once
// prefixed, a malformed filter still sits under the tenant's name, but it does
// not mean what the tenant intended, and a permission that does not mean what
// was intended is worth refusing.
func validPatterns(field string, pats []string, prefix string) error {
	if len(pats) == 0 {
		return fmt.Errorf("%s must have at least one pattern", field)
	}
	if len(pats) > maxPatterns {
		return fmt.Errorf("%s has %d patterns, the limit is %d", field, len(pats), maxPatterns)
	}
	for i, p := range pats {
		where := fmt.Sprintf("%s pattern %d", field, i+1)
		switch {
		case p == "":
			return fmt.Errorf("%s is empty", where)
		case len(p) > maxPattern:
			return fmt.Errorf("%s is longer than %d characters", where, maxPattern)
		case !strings.HasPrefix(p, prefix):
			// Deliberately does not echo the pattern: an error message is not
			// a place to reflect a caller's string back over the wire.
			return fmt.Errorf("%s is not under the tenant prefix %q", where, prefix)
		case strings.ContainsRune(p, '%'):
			// % starts a VerneMQ template variable. The API chooses usernames,
			// so there is nothing a tenant could want one for.
			return fmt.Errorf("%s contains %%", where)
		}
		if err := validWildcards(where, p); err != nil {
			return err
		}
	}
	return nil
}

// validWildcards applies MQTT 3.1.1 §4.7: + occupies a whole level, and #
// is the last character of the filter.
func validWildcards(where, pat string) error {
	levels := strings.Split(pat, "/")
	for i, lvl := range levels {
		if strings.Contains(lvl, "+") && lvl != "+" {
			return fmt.Errorf("%s uses + outside a whole level", where)
		}
		if strings.Contains(lvl, "#") {
			if lvl != "#" {
				return fmt.Errorf("%s uses # outside a whole level", where)
			}
			if i != len(levels)-1 {
				return fmt.Errorf("%s uses # before the end of the filter", where)
			}
		}
	}
	return nil
}
